import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

//Contexts
import { ThemeProvider } from "@/contexts/themeContext";
import { DrawerProvider } from "@/contexts/drawerContext"; // Added import
import Drawer from "@/components/drawer/drawer"; // Import the Drawer component

//Fonts
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

//Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Scripts
// Esse script é executa antes do React no cliente, deixando o tema correto
// e evitando o efeito de flash de tema (FOUC).
const ThemeInitializerScript = () => (
  <script
    dangerouslySetInnerHTML={{
      __html: `
        (function() {
          try {
            const storedTheme = localStorage.getItem('user_theme');
            let theme = '';
            if (storedTheme === '' || storedTheme === 'dark') {
              theme = storedTheme;
            } else if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
              theme = 'dark';
            }
            document.documentElement.classList.remove('dark');
            document.documentElement.classList.add(theme);
          } catch (e) {}
        })();
      `,
    }}
  />
);

const MaterialIcons = () => (  
  //Tive que remover o warning do eslint.
  // NextJS reclama de importar fontes externas Google (já que são nativas), porém são Icons
  // eslint-disable-next-line 
  <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
);

type Layout = Readonly<{children: React.ReactNode}>;

//Layout
export default function RootLayout({children}: Layout){
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
      <MaterialIcons />
      <ThemeInitializerScript />
      </head>
      <body className={` ${montserrat.variable} antialiased`}>
        <ThemeProvider>
          <DrawerProvider>
            <Drawer /> 
            {children}
          </DrawerProvider> 
        </ThemeProvider>
      </body>
    </html>
  );
}
